source 'https://github.com/CocoaPods/Specs.git'
platform :ios,"7.0"
pod 'AFNetworking', '~> 2.5.0'
pod 'MagicalRecord'
pod 'Qiniu', '~> 7.0.8'
pod 'RongCloudIMKit’, '1.3.3'
pod 'SDWebImage', '~> 3.7.1'
pod 'TTTAttributedLabel', '~> 1.13.1'
pod 'GPUImage'
pod 'UMengAnalytics-NO-IDFA'
